Update patch set 2
Patch Set 2:

this introduced - 
hardware/qcom/media-caf/msm8937/mm-video-v4l2/vidc/vdec/inc/omx_vdec.h:52:10: fatal error: 'color_metadata.h' file not found
#include <color_metadata.h>

Patch-set: 2