Update patch set 11
Patch Set 11: Code-Review+1

The code is fine now your issue
hardware/qcom/media/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp:3380:34: error: 'V4L2_CID_MPEG_VIDC_VIDEO_ALLOC_MODE_OUTPUT' was not declared in this scope
hardware/qcom/media/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp:3381:37: error: 'V4L2_MPEG_VIDC_VIDEO_DYNAMIC' was not declared in this scope
Is that it is forcing you to use the headers from qcom/display-mdss now which has not been updated for kk

Patch-set: 11
Label: Code-Review=+1