Update patch set 3
Patch Set 3:

This totally breaks the build for shamu

hardware/qcom/media/default/mm-video-v4l2/vidc/venc/inc/omx_video_base.h:108:27: error: 'struct ion_allocation_data' has no member named 'heap_id_mask'
     #define ION_HEAP_MASK heap_id_mask
                           ^
hardware/qcom/media/default/mm-video-v4l2/vidc/venc/src/omx_video_base.cpp:4239:21: note: in expansion of macro 'ION_HEAP_MASK'
         alloc_data->ION_HEAP_MASK = ION_HEAP(ION_CP_MM_HEAP_ID);

Patch-set: 3
Reviewer: David Hacker <8640@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0